[build]
  publish = "build/"
  command = "yarn build"

  # Develop Branch Deploy context: All deploys that are not in
  # an active Deploy Preview will inherit these settings.
[context.develop]
  [context.develop.environment]
  NODE_VERSION = "11.0.0"
  REACT_APP_DEV_ARBITRATOR_ADDRESS = "0xB1B826Dad302c55Fd021E9E84DEFDFc94BEfa780"
  REACT_APP_DEV_ARBITRABLE_ADDRESS = "0xa438E5338f3cb55442a1206567adA2636eed3473"
  REACT_APP_DEV_FEE_TIMEOUT= "240"
  REACT_APP_ARBITRATOR_EXTRADATA = "0x00"
  REACT_APP_DEV_IPFS_PROVIDER = ""
  YARN_FLAGS = "--no-ignore-optional"
# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  [context.production.environment]
  NODE_VERSION = "11.0.0"
  REACT_APP_PROD_ARBITRATOR_ADDRESS = "0xB1B826Dad302c55Fd021E9E84DEFDFc94BEfa780"
  REACT_APP_PROD_ARBITRABLE_ADDRESS = "0xa438E5338f3cb55442a1206567adA2636eed3473"
  REACT_APP_PROD_FEE_TIMEOUT= "172800"
  REACT_APP_ARBITRATOR_EXTRADATA = "0x00"
  REACT_APP_PROD_IPFS_PROVIDER = ""
  YARN_FLAGS = "--no-ignore-optional"
