[build]
  publish = "build/"
  command = "yarn build"

  # Develop Branch Deploy context: All deploys that are not in
  # an active Deploy Preview will inherit these settings.
[context.develop]
  [context.develop.environment]
  NODE_VERSION = "11.0.0"
  REACT_APP_DEV_ARBITRATOR_ADDRESS = "0xB1B826Dad302c55Fd021E9E84DEFDFc94BEfa780"
  REACT_APP_DEV_ARBITRABLE_ADDRESS = "0x3d7A9f7C1A36Bc6b9C9E8C9b34605d818D33612f"
  REACT_APP_DEV_FEE_TIMEOUT= "240"
  REACT_APP_ARBITRATOR_EXTRADATA = "0x00"
  REACT_APP_DEV_IPFS_PROVIDER = ""
  YARN_FLAGS = "--no-ignore-optional"
# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  [context.production.environment]
  NODE_VERSION = "11.0.0"
  REACT_APP_PROD_ARBITRATOR_ADDRESS = "0xB1B826Dad302c55Fd021E9E84DEFDFc94BEfa780"
  REACT_APP_PROD_ARBITRABLE_ADDRESS = "0x3d7A9f7C1A36Bc6b9C9E8C9b34605d818D33612f"
  REACT_APP_PROD_FEE_TIMEOUT= "240"
  REACT_APP_ARBITRATOR_EXTRADATA = "0x00"
  REACT_APP_PROD_IPFS_PROVIDER = ""
  YARN_FLAGS = "--no-ignore-optional"
# Branch Athena context.
[context.athena-escrow]
  [context.athena-escrow.environment]
  REACT_APP_PROD_ARBITRATOR_ADDRESS = "0x8847c0947a613c3de443f73351c3815ad0d37f98"
  REACT_APP_PROD_ARBITRABLE_ADDRESS = "0xdff38d64aa40fb55d3ac264e792bef5b28e03c01"
