[build]
  publish = "build/"
  command = "yarn build"

  # Develop Branch Deploy context: All deploys that are not in
  # an active Deploy Preview will inherit these settings.
[context.develop]
  [context.develop.environment]
  NODE_VERSION = "11.0.0"
  REACT_APP_DEV_ARBITRATOR_ADDRESS = "0xb4abf7c26818e0b7f82bb0af2154deb0c9b54ed0"
  REACT_APP_DEV_ARBITRABLE_ADDRESS = "0x19fb99e3ff370b26f70d6382c3db3c7ffad773d6"
  REACT_APP_ARBITRATOR_EXTRADATA = "0x00"
  REACT_APP_ARBITRATOR_TIMEOUT = "172800"
  REACT_APP_DEV_IPFS_PROVIDER = ""
  YARN_FLAGS = "--no-ignore-optional"
# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  [context.production.environment]
  NODE_VERSION = "11.0.0"
  REACT_APP_PROD_ARBITRATOR_ADDRESS = "0xb4abf7c26818e0b7f82bb0af2154deb0c9b54ed0"
  REACT_APP_PROD_ARBITRABLE_ADDRESS = "0x19fb99e3ff370b26f70d6382c3db3c7ffad773d6"
  REACT_APP_ARBITRATOR_EXTRADATA = "0x00"
  REACT_APP_ARBITRATOR_TIMEOUT = "172800"
  REACT_APP_PROD_IPFS_PROVIDER = ""
  YARN_FLAGS = "--no-ignore-optional"
