[build.environment]
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_PROD_ETHEREUM_PROVIDER_URL='https://kovan.infura.io/v3/8886cb30669f45a19e3c42a0d81d7ebd'
  REACT_APP_PROD_ARBITRATOR_ADDRESS='0x60b2abfdfad9c0873242f59f2a8c32a3cc682f80'
  REACT_APP_PROD_ARBITRABLE_NONTECHNICAL_ADDRESS='0x362cdd79fe1a150fc58945029669a00ae06981b9'
  REACT_APP_PROD_PATCH_USER_SETTINGS_URL='https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/user-settings'

[context.production.environment]
  REACT_APP_PROD_ETHEREUM_PROVIDER_URL='https://mainnet.infura.io/v3/8886cb30669f45a19e3c42a0d81d7ebd'
  REACT_APP_PROD_ARBITRATOR_ADDRESS='0x988b3a538b618c7a603e1c11ab82cd16dbe28069'
  REACT_APP_PROD_ARBITRABLE_NONTECHNICAL_ADDRESS='0x5906db495c9f27f73a9c46790cc79d860a6e9b5d'
  REACT_APP_PROD_PATCH_USER_SETTINGS_URL='https://hgyxlve79a.execute-api.us-east-2.amazonaws.com/production/user-settings'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
