[build.environment]
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_PROD_ETHEREUM_PROVIDER_URL='https://kovan.infura.io/v3/8886cb30669f45a19e3c42a0d81d7ebd'
  REACT_APP_PROD_ARBITRATOR_ADDRESS='0x60b2abfdfad9c0873242f59f2a8c32a3cc682f80'
  REACT_APP_PROD_ARBITRABLE_NONTECHNICAL_ADDRESS='0x01171b3fb9627dd127a6ceb356b4470c492e7a8d'
  REACT_APP_PROD_PATCH_USER_SETTINGS_URL='https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/user-settings'

[context.production.environment]
  REACT_APP_PROD_ETHEREUM_PROVIDER_URL='https://mainnet.infura.io/v3/8886cb30669f45a19e3c42a0d81d7ebd'
  REACT_APP_PROD_ARBITRATOR_ADDRESS='0x988b3a538b618c7a603e1c11ab82cd16dbe28069'
  REACT_APP_PROD_ARBITRABLE_NONTECHNICAL_ADDRESS='0xE2Dd8CCe2c33a04215074ADb4B5820B765d8Ed9D'
  REACT_APP_PROD_PATCH_USER_SETTINGS_URL='https://hgyxlve79a.execute-api.us-east-2.amazonaws.com/production/user-settings'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
